### ISSUE TITLE
There was an error invoking Hub method 'c2.Authenticate'.

### ISSUE THREAD

**Issue by ape364** [nanvel/aiobittrex#3]
Hi.

I'm trying to fetch account updates:
```
import asyncio

import aiobittrex

creds = dict(
    api_key='...',
    api_secret='...'
)


async def main():
    s = aiobittrex.BittrexSocket(**creds)
    async for msg in s.listen_account():
        print(msg)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

Getting error:
```
Traceback (most recent call last):
  File "/opt/pycharm-professional/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/opt/pycharm-professional/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-professional/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-professional/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ape364/test/aiobitra/bittrex_ws_test.py", line 26, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/home/ape364/test/aiobitra/bittrex_ws_test.py", line 20, in main
    async for msg in s.listen_account():
  File "/home/ape364/test/venv/lib/python3.7/site-packages/aiobittrex/socket.py", line 186, in listen_account
    messages=[[self.api_key, signature]]):
  File "/home/ape364/test/venv/lib/python3.7/site-packages/aiobittrex/socket.py", line 153, in _listen
    raise BittrexError(message=decoded_message['E'])
aiobittrex.errors.BittrexError: BittrexError: There was an error invoking Hub method 'c2.Authenticate'.
```

Tried on both 0.0.4 and 0.1.0 versions of aiobittrex. Is this a server-side problem?

**Comment by nanvel** [comment]
https://github.com/Bittrex/bittrex.github.io/issues/16

For me the error is "There was an error invoking Hub method 'c2.GetAuthContext'."

**Comment by ape364** [comment]
from time to time it works with implicit WS connection, but with the explicit connection it works every time (i tried ~15 times)

explicit example:
```
async def main():
    s = aiobittrex.BittrexSocket(api_key=creds['api_key'], api_secret=creds['api_secret'], loop=loop)
    ws = await s.create_ws()
    async for msg in s.listen_account(ws):
        print(msg)
```
